name: Conan

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install Conan
      run: |
          pip install conan
          conan profile new default --detect

    - name: Create conan package
      run: conan create .
