name: Lint

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install Conan
      run: |
          pip install conan
          conan profile new default --detect

    - name: Update Homebrew taps
      run: brew update

    - name: Install clang-format & clang-tidy
      run: |
          brew install llvm
          ln -s "$(brew --prefix llvm)/bin/clang-format" "/usr/local/bin/clang-format"
          ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DVIOLET_WARNINGS_AS_ERRORS=ON

    - name: Build
      run: cmake --build build
